language: python
python:
 - 2.7
 - 3.4

addons:
 postgresql: "9.4"

env:
 - APP_SETTINGS="config.DevelopmentConfig"

before_script:
 - psql -U postgres -c "create database url;"

install:
 - pip install -r requirements.txt

script:
 - python db_create.py
 - python web.py

