language: python
python:
 - 2.7

addons:
 postgresql: "9.4"

env:
 - APP_SETTINGS="config.DevelopmentConfig"

before_script:
 - psql -U postgres -c "create database urls;"

install:
 - pip install -r requirements.txt

script:
# run simple test on development db
# - python db_create.py
# - python test.py

# run tests against test db
 - python manage.py test

